modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/EnchantableBlocks/issues"
license="MIT"

[[mods]]
modId="enchantableblocks"
version="${file.jarVersion}"
displayName="Enchantable Blocks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enchantable-blocks"
authors="Mrbysco"
description='''
Allows enchanting of some blocks to change how they function
'''


[[dependencies.enchantableblocks]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.enchantableblocks]]
modId="neoforge"
type="required"
versionRange="[20.4.167,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="enchantableblocks.mixins.json"